"""Allowlisted public and internal enum values."""

from enum import StrEnum


class Locale(StrEnum):
    ENGLISH = "en"
    HINDI = "hi"


class Service(StrEnum):
    LEARNER_LICENCE = "learner-licence"
    LEARNER_TEST = "learner-test"
    PERMANENT_DRIVING_LICENCE = "permanent-driving-licence"
    RENEWAL = "renewal"
    DUPLICATE_REPLACEMENT = "duplicate-replacement"
    CHANGE_ADDRESS = "change-address"
    MOBILE_UPDATE = "mobile-update"
    APPLICATION_STATUS = "application-status"
    FEES_PAYMENT = "fees-payment"
    APPOINTMENT_WAITLIST = "appointment-waitlist"


class Page(StrEnum):
    DASHBOARD = "dashboard"
    GUIDED_APPLICATION = "guided-application"
    LEARNER_TEST = "learner-test"
    ELIGIBILITY = "eligibility"
    APPLICATION_STATUS = "application-status"
    PAYMENT = "payment"
    APPOINTMENT_BOOKING = "appointment-booking"
    APPOINTMENT_WAITLIST = "appointment-waitlist"
    APPOINTMENT_OFFER = "appointment-offer"
    PREPARATION_CHECKLIST = "preparation-checklist"
    SIMULATION_DISCLOSURE = "simulation-disclosure"
    ASSISTANT = "assistant"


class ReasonCode(StrEnum):
    NONE = "NONE"
    ACTION_LOCKED = "ACTION_LOCKED"
    WAITING_PERIOD_ACTIVE = "WAITING_PERIOD_ACTIVE"
    LEARNER_LICENCE_EXPIRED = "LEARNER_LICENCE_EXPIRED"
    NO_MATCHING_SLOT = "NO_MATCHING_SLOT"
    WAITLIST_ACTIVE = "WAITLIST_ACTIVE"
    OFFER_PENDING = "OFFER_PENDING"
    OFFER_EXPIRED = "OFFER_EXPIRED"
    SIMULATED_ACTION = "SIMULATED_ACTION"
    PREPARATION_REQUIRED = "PREPARATION_REQUIRED"


class CanonicalIntent(StrEnum):
    CURRENT_STEP_EXPLANATION = "CURRENT_STEP_EXPLANATION"
    LOCKED_ACTION_EXPLANATION = "LOCKED_ACTION_EXPLANATION"
    WAITING_PERIOD_EXPLANATION = "WAITING_PERIOD_EXPLANATION"
    LEARNER_LICENCE_EXPIRY_EXPLANATION = "LEARNER_LICENCE_EXPIRY_EXPLANATION"
    NO_APPOINTMENT_EXPLANATION = "NO_APPOINTMENT_EXPLANATION"
    WAITLIST_EXPLANATION = "WAITLIST_EXPLANATION"
    OFFER_EXPIRY_EXPLANATION = "OFFER_EXPIRY_EXPLANATION"
    MOCK_VS_REAL_EXPLANATION = "MOCK_VS_REAL_EXPLANATION"
    PREPARATION_CHECKLIST_EXPLANATION = "PREPARATION_CHECKLIST_EXPLANATION"
    UNSUPPORTED_QUESTION = "UNSUPPORTED_QUESTION"


class Topic(StrEnum):
    LEARNER_LICENCE_APPLICATION = "LEARNER_LICENCE_APPLICATION"
    LEARNER_TEST = "LEARNER_TEST"
    PERMANENT_LICENCE_APPLICATION = "PERMANENT_LICENCE_APPLICATION"
    RENEWAL = "RENEWAL"
    DUPLICATE_REPLACEMENT = "DUPLICATE_REPLACEMENT"
    CHANGE_ADDRESS = "CHANGE_ADDRESS"
    MOBILE_UPDATE = "MOBILE_UPDATE"
    APPLICATION_STATUS = "APPLICATION_STATUS"
    FEES_PAYMENT = "FEES_PAYMENT"
    APPOINTMENT = "APPOINTMENT"
    WAITLIST = "WAITLIST"
    SLOT_OFFER = "SLOT_OFFER"
    PREPARATION = "PREPARATION"
    SIMULATION = "SIMULATION"


class DlpAction(StrEnum):
    ALLOW = "ALLOW"
    BLOCK_PROVIDER_WITH_LOCAL_HELP = "BLOCK_PROVIDER_WITH_LOCAL_HELP"
    UNSUPPORTED = "UNSUPPORTED"
    FAIL_CLOSED = "FAIL_CLOSED"


class DlpScope(StrEnum):
    INBOUND = "INBOUND"
    PROVIDER_PAYLOAD = "PROVIDER_PAYLOAD"
    OUTBOUND = "OUTBOUND"


class BlockedReason(StrEnum):
    PII_DETECTED = "PII_DETECTED"
    UNSUPPORTED = "UNSUPPORTED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    NO_EVIDENCE = "NO_EVIDENCE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    INVALID_OUTPUT = "INVALID_OUTPUT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_SAFETY_FAILURE = "INTERNAL_SAFETY_FAILURE"


class EscalationCode(StrEnum):
    REVIEW_PUBLIC_GUIDANCE = "REVIEW_PUBLIC_GUIDANCE"
    CONTACT_PROTOTYPE_SUPPORT = "CONTACT_PROTOTYPE_SUPPORT"
